# Following services are included:
# - mongodb: MongoDB (exposed port: 27017)
# - arangodb: ArangoDB (exposed port: 8529)
# - postgres14: PostgresSQL (exposed port: 5432)
# - postgres12: PostgresSQL (exposed port: 5433)
# - TimescaleDB: TimescaleDB (exposed port: 5434)
# - pgadmin4: pgAdmin4 (exposed port: 9901)
# - rabbitmq: RabbitMQ (exposed ports: 5672, 15672)
# - elasticsearch: Elasticsearch (exposed ports: 9200, 9300)
# - elasticsearch-noauth: Elasticsearch (exposed ports: 9200, 9300)
# - fluentbit: FluentD (exposed ports: 24224)
# - fluentd: FluentBit (exposed ports: 24224)

# Network
# You have to manually create a docker network first:
# " $docker network create mydevnetwork "



version: "3.8"
services:

  # MongoDB
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - mydevnetwork
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mydevuser
      - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword123**

  # ArangoDB
  arangodb:
    platform: linux/x86_64/v8
    container_name: arangodb
    image: arangodb:3.8
    restart: "unless-stopped"
    ports:
      - "8529:8529"
    networks:
      - mydevnetwork
    volumes:
      - arangodb:/var/lib/arangodb3
    environment:
      - ARANGO_NO_AUTH=1
      - MONGO_INITDB_ROOT_PASSWORD=mysecretpassword123**

  # Elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mydevnetwork
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=mysecretpassword123**

  # Elasticsearch
  elasticsearch-noauth:
    container_name: eslasticsearch-noauth
    image: elasticsearch:7.16.1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - mydevnetwork
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - network.host=0.0.0.0

  # Postgres14
  postgres14:
    container_name: postgres14
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mydevuser
      POSTGRES_PASSWORD: mysecretpassword123**
    volumes:
      - postgres14:/data/postgres
    networks:
      - mydevnetwork

  # Postgres12
  postgres12:
    container_name: postgres12
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: mydevuser
      POSTGRES_PASSWORD: mysecretpassword123**
    volumes:
      - postgres12:/data/postgres
    networks:
      - mydevnetwork

  # pgAdmin4
  pgadmin4:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: "unless-stopped"
    ports:
      - "9901:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mydevuser@domain.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword123**
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - mydevnetwork

  # TimescaleDB
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb
    restart: "unless-stopped"
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - timescaledb:/var/lib/postgresql/data

  # Kibana
  kibana:
    container_name: kibana
    image: kibana:7.16.1
    ports:
      - "5601:5601"
    networks:
      - mydevnetwork
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana
      - ELASTICSEARCH_PASSWORD=mysecretpassword123**

  kibana-es-noauth:
    container_name: kibana-es-noauth
    image: kibana:7.16.1
    ports:
      - "5601:5601"
    networks:
      - mydevnetwork
    environment:
      - ELASTICSEARCH_HOSTS=http://eslasticsearch-noauth:9200

  # RabbitMQ
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: mydevuser
      RABBITMQ_DEFAULT_PASS: mysecretpassword123**
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - mydevnetwork

  # Fluenbit
  fluentbit:
    container_name: fluentbit
    image: fluent/fluent-bit
    restart: "unless-stopped"
    ports:
      - "24224:24224"
    volumes:
      - ./fluent-bit/etc:/fluent-bit/etc/  # config
    networks:
      - mydevnetwork

  # Fluend
  fluentd:
    container_name: fluentd
    image: fluent/fluentd
    restart: "unless-stopped"
    ports:
      - "24224:24224"
    environment:
      RABBITMQ_DEFAULT_USER: mydevuser
      RABBITMQ_DEFAULT_PASS: mysecretpassword123**
    volumes:
      - fluentd:/fluentd/log
      - ./fluentd/etc:/fluentd/etc  # config
    networks:
      - mydevnetwork

volumes:
  mongodb:
  arangodb:
  elasticsearch:
  postgres14:
  postgres12:
  timescaledb:
  pgadmin:
  rabbitmq:
  fluentd:

networks:
 mydevnetwork:

