version: "3.8"

services:
  pgAdmin4:
    container_name: pgAdmin4
    image: dpage/pgadmin4
    ports:
      - "8000:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: mydevuser@domain.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword123**
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - mydevnetwork

volumes:
  pgadmin:

networks:
 mydevnetwork:
   external: true
   name: mydevnetwork