version: "3"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - local-infra-net1
    environment:
      # If there is an existing MongoDB, these are ignored.
      # So change your admin/admin root user after database first run!
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

  rabbitmq:
    container_name: rabbitmq
    # platform: linux/amd64
    build:
      context: ./rabbitmq
    ports:
      - "15672:15672"
      # - "5672:5672"
    networks:
      - local-infra-net1
    environment:
      RABBITMQ_DEFAULT_USER: rabbit
      RABBITMQ_DEFAULT_PASS: rabbit

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.16.1
    ports:
      - "9200:9200"
      # - "9300:9300"
    networks:
      - local-infra-net1
    environment:
      - xpack.security.enabled=true
      - xpack.security.authc.api_key.enabled=true
      - discovery.type=single-node
      - network.host=0.0.0.0
      - ELASTIC_PASSWORD=elastic_password

  kibana:
    container_name: kibana
    image: kibana:7.16.1
    ports:
      - "5601:5601"
    networks:
      - local-infra-net1
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic_password
  logstash:
    container_name: logstash
    build:
      context: ./logstash
    volumes:
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
    networks:
      - local-infra-net1

networks:
  local-infra-net1:
    driver: bridge