version: "3.8"

services:
  mq:
    container_name: mq
    image: rabbitmq:3-management
    restart: "unless-stopped"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: mydevuser
      RABBITMQ_DEFAULT_PASS: mysecretpassword123**
    networks:
      - mydevnetwork

networks:
 mydevnetwork:
   external: true
   name: mydevnetwork